name: Multi Bluesky Reposter (3-hourly)

on:
  workflow_dispatch:
  schedule:
    - cron: "42 */3 * * *"

jobs:
  run-multi-reposter:
    runs-on: ubuntu-latest

    env:
      BSKY_USERNAME_BEAUTYFAN: ${{ secrets.BSKY_USERNAME_BEAUTYFAN }}
      BSKY_PASSWORD_BEAUTYFAN: ${{ secrets.BSKY_PASSWORD_BEAUTYFAN }}

      BSKY_USERNAME_BEAUTYGROUP: ${{ secrets.BSKY_USERNAME_BEAUTYGROUP }}
      BSKY_PASSWORD_BEAUTYGROUP: ${{ secrets.BSKY_PASSWORD_BEAUTYGROUP }}

      BSKY_USERNAME_HOTBLEUSKY: ${{ secrets.BSKY_USERNAME_HOTBLEUSKY }}
      BSKY_PASSWORD_HOTBLEUSKY: ${{ secrets.BSKY_PASSWORD_HOTBLEUSKY }}

      BSKY_USERNAME_BLEUSKYPROMO: ${{ secrets.BSKY_USERNAME_BLEUSKYPROMO }}
      BSKY_PASSWORD_BLEUSKYPROMO: ${{ secrets.BSKY_PASSWORD_BLEUSKYPROMO }}

      BSKY_USERNAME_NSFWBLEUSKY: ${{ secrets.BSKY_USERNAME_NSFWBLEUSKY }}
      BSKY_PASSWORD_NSFWBLEUSKY: ${{ secrets.BSKY_PASSWORD_NSFWBLEUSKY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atproto

      - name: Run multi_reposter_luanablack2
        run: python multi_reposter_luanablack2.py

      - name: Run multi_reposter_nakedneighbour1985
        run: python multi_reposter_nakedneighbour1985.py

      - name: Run multi_reposter_grovel4maeve
        run: python multi_reposter_grovel4maeve.py